/*
 * App URI: app/cmn/exbuilderTemplate
 * Source Location: app/cmn/exbuilderTemplate.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("app/cmn/exbuilderTemplate", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("dsSum");
			dataSet_1.parseData({
				"columns": [
					{"name": "OG"},
					{"name": "SA"},
					{"name": "STUD_CNT"},
					{"name": "OUT_STUD_CNT"},
					{"name": "OG"},
					{"name": "SA"},
					{"name": "STUD_CNT"},
					{"name": "OUT_STUD_CNT"},
					{"name": "OG"},
					{"name": "SA"},
					{"name": "STUD_CNT"},
					{"name": "OUT_STUD_CNT"}
				],
				"rows": []
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("dsLsbPgmInfo");
			dataSet_2.parseData({
				"columns": [
					{"name": "pgm_id"},
					{"name": "pgm_nm"}
				],
				"rows": []
			});
			app.register(dataSet_2);
			
			var dataSet_3 = new cpr.data.DataSet("dsMsgDivRcdList");
			dataSet_3.parseData({
				"columns": [
					{"name": "UPD_DTHR"},
					{"name": "UPD_USER_ID"},
					{"name": "CRT_PGM_ID"},
					{"name": "UCD"},
					{"name": "UPD_PGM_ID"},
					{"name": "CD_LEN"},
					{"name": "OG_CD"},
					{"name": "CD_PRP10"},
					{"name": "ULAN_DIV_RCD"},
					{"name": "CD_PRP2"},
					{"name": "CD_PRP3"},
					{"name": "CRT_DTHR"},
					{"name": "CD_PRP4"},
					{"name": "CRT_IP_MAC"},
					{"name": "CRT_USER_ID"},
					{"name": "CD_PRP5"},
					{"name": "CD_PRP6"},
					{"name": "CD_PRP7"},
					{"name": "CD_PRP8"},
					{"name": "CD_DESC"},
					{"name": "CD_PRP9"},
					{"name": "UNIT_SYSTEM_RCD"},
					{"name": "OG_NM"},
					{"name": "CD_SHORT_NM"},
					{"name": "UPD_IP_MAC"}
				],
				"rows": []
			});
			app.register(dataSet_3);
			
			var dataSet_4 = new cpr.data.DataSet("dsMsgSubDivRcdList");
			dataSet_4.parseData({
				"columns": [
					{"name": "UPD_DTHR"},
					{"name": "UPD_USER_ID"},
					{"name": "CRT_PGM_ID"},
					{"name": "UPD_PGM_ID"},
					{"name": "CD_LEN"},
					{"name": "OG_CD"},
					{"name": "CD_PRP10"},
					{"name": "ULAN_DIV_RCD"},
					{"name": "CD_PRP2"},
					{"name": "CD_PRP3"},
					{"name": "CRT_DTHR"},
					{"name": "CD_PRP4"},
					{"name": "CRT_IP_MAC"},
					{"name": "CRT_USER_ID"},
					{"name": "CD_PRP5"},
					{"name": "CD_PRP6"},
					{"name": "CD_PRP7"},
					{"name": "CD_PRP8"},
					{"name": "CD_DESC"},
					{"name": "CD_PRP9"},
					{"name": "UNIT_SYSTEM_RCD"},
					{"name": "OG_NM"},
					{"name": "CD_SHORT_NM"},
					{"name": "UPD_IP_MAC"}
				],
				"rows": []
			});
			app.register(dataSet_4);
			var dataMap_1 = new cpr.data.DataMap("dmReqList");
			dataMap_1.parseData({
				"columns" : [
					{
						"name": "strMsgDivRcd",
						"dataType": "string"
					},
					{
						"name": "strMsgSubDivRcd",
						"dataType": "string"
					}
				]
			});
			app.register(dataMap_1);
			
			var dataMap_2 = new cpr.data.DataMap("dmSelect");
			dataMap_2.parseData({
				"columns" : [{
					"name": "listbox1",
					"dataType": "string"
				}]
			});
			app.register(dataMap_2);
			
			var dataMap_3 = new cpr.data.DataMap("dmEtc");
			dataMap_3.parseData({
				"columns" : [{
					"name": "listbox2",
					"dataType": "string"
				}]
			});
			app.register(dataMap_3);
			
			var dataMap_4 = new cpr.data.DataMap("dmValid");
			dataMap_4.parseData({
				"columns" : [
					{
						"name": "strInput",
						"dataType": "string"
					},
					{
						"name": "strCbb",
						"dataType": "string"
					},
					{
						"name": "strInput2",
						"dataType": "string"
					}
				]
			});
			app.register(dataMap_4);
			var submission_1 = new cpr.protocols.Submission("subExbInfo");
			submission_1.action = "/cmn/StdCmnTmpTemplate/";
			submission_1.mediaType = "application/x-www-form-urlencoded";
			submission_1.addResponseData(dataSet_2, false);
			app.register(submission_1);
			
			app.supportMedia("all and (min-width: 1235px)", "default");
			app.supportMedia("all and (min-width: 1020px) and (max-width: 1234px)", "notebook");
			app.supportMedia("all and (min-width: 760px) and (max-width: 1019px)", "tablet");
			app.supportMedia("all and (max-width: 759px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grpSearch");
			group_1.style.setClasses(["search-box"]);
			// Layout
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
			})(group_1);
			container.addChild(group_1, {
				"top": "35px",
				"left": "5px",
				"width": "1225px",
				"height": "32px"
			});
			
			var userDefinedControl_1 = new udc.com.appHeader("appheader1");
			container.addChild(userDefinedControl_1, {
				"top": "5px",
				"right": "5px",
				"left": "5px",
				"height": "25px"
			});
			
			var group_2 = new cpr.controls.Container("grpData");
			// Layout
			var xYLayout_3 = new cpr.controls.layouts.XYLayout();
			group_2.setLayout(xYLayout_3);
			(function(container){
				var tabFolder_1 = new cpr.controls.TabFolder("tabMain");
				
				var tabItem_1 = (function(tabFolder){
					var tabItem_1 = new cpr.controls.TabItem();
					tabItem_1.text = "tab1";
					tabItem_1.name = "Repeat";
					var group_3 = new cpr.controls.Container("grpRepeat");
					// Layout
					var formLayout_1 = new cpr.controls.layouts.FormLayout();
					formLayout_1.topMargin = "0px";
					formLayout_1.rightMargin = "0px";
					formLayout_1.bottomMargin = "0px";
					formLayout_1.leftMargin = "0px";
					formLayout_1.horizontalSpacing = "0px";
					formLayout_1.verticalSpacing = "0px";
					formLayout_1.setColumns(["1fr"]);
					formLayout_1.setRows(["1fr"]);
					group_3.setLayout(formLayout_1);
					(function(container){
						var grid_1 = new cpr.controls.Grid("grdSum");
						grid_1.init({
							"dataSet": app.lookup("dsSum"),
							"columns": [
								{"width": "177px"},
								{"width": "144px"},
								{"width": "84px"},
								{"width": "80px"}
							],
							"header": {
								"rows": [{"height": "27px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.text = "학부";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.text = "학과";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.text = "재학생수";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.text = "휴학생수";
										}
									}
								]
							},
							"detail": {
								"rows": [{"height": "25px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.columnName = "OG";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 1},
										"configurator": function(cell){
											cell.columnName = "SA";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.columnName = "STUD_CNT";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 3},
										"configurator": function(cell){
											cell.columnName = "OUT_STUD_CNT";
										}
									}
								]
							},
							"footer": {
								"rows": [{"height": "25px"}],
								"cells": [
									{
										"constraint": {"rowIndex": 0, "colIndex": 0},
										"configurator": function(cell){
											cell.expr = "\"합계\"";
										}
									},
									{
										"constraint": {"rowIndex": 0, "colIndex": 2},
										"configurator": function(cell){
											cell.expr = "getSum(\"text()\")";
										}
									}
								]
							}
						});
						container.addChild(grid_1, {
							"top": "30px",
							"left": "5px",
							"width": "605px",
							"height": "268px"
						});
						var userDefinedControl_2 = new udc.com.comFormTitle();
						userDefinedControl_2.bind("title").toLanguage("");
						container.addChild(userDefinedControl_2, {
							"top": "5px",
							"left": "5px",
							"width": "150px",
							"height": "25px"
						});
						var output_1 = new cpr.controls.Output("label5");
						output_1.value = "소계대상 디테일 컬럼의 Suppress=true 지정, 그룹추가";
						container.addChild(output_1, {
							"top": "5px",
							"left": "105px",
							"width": "425px",
							"height": "25px"
						});
					})(group_3);
					tabItem_1.content = group_3;
					return tabItem_1;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_1);
				
				var tabItem_2 = (function(tabFolder){
					var tabItem_2 = new cpr.controls.TabItem();
					tabItem_2.text = "tab1";
					tabItem_2.name = "Select";
					var group_4 = new cpr.controls.Container("grpSelect");
					// Layout
					var formLayout_2 = new cpr.controls.layouts.FormLayout();
					formLayout_2.topMargin = "0px";
					formLayout_2.rightMargin = "0px";
					formLayout_2.bottomMargin = "0px";
					formLayout_2.leftMargin = "0px";
					formLayout_2.horizontalSpacing = "0px";
					formLayout_2.verticalSpacing = "0px";
					formLayout_2.setColumns(["1fr"]);
					formLayout_2.setRows(["1fr"]);
					group_4.setLayout(formLayout_2);
					(function(container){
						var output_2 = new cpr.controls.Output("optMsgDivRcd");
						output_2.value = "대구분";
						container.addChild(output_2, {
							"top": "35px",
							"left": "5px",
							"width": "60px",
							"height": "25px"
						});
						var comboBox_1 = new cpr.controls.ComboBox("cbbMsgDivRcd");
						comboBox_1.bind("fieldLabel").toExpression("#optMsgDivRcd.value");
						(function(comboBox_1){
							comboBox_1.setItemSet(app.lookup("dsMsgDivRcdList"), {
								"label": "CD_NM",
								"value": "CD"
							});
						})(comboBox_1);
						if(typeof onCbbMsgDivRcdSelectionChange == "function") {
							comboBox_1.addEventListener("selection-change", onCbbMsgDivRcdSelectionChange);
						}
						container.addChild(comboBox_1, {
							"top": "35px",
							"left": "70px",
							"width": "130px",
							"height": "25px"
						});
						var output_3 = new cpr.controls.Output("optMsgSubDivRcd");
						output_3.value = "소구분";
						container.addChild(output_3, {
							"top": "35px",
							"left": "205px",
							"width": "55px",
							"height": "25px"
						});
						var comboBox_2 = new cpr.controls.ComboBox("cbbMsgSubDivRcd");
						comboBox_2.bind("fieldLabel").toExpression("#optMsgSubDivRcd.value");
						(function(comboBox_2){
							comboBox_2.setItemSet(app.lookup("dsMsgSubDivRcdList"), {
								"label": "CD_NM",
								"value": "CD"
							});
						})(comboBox_2);
						container.addChild(comboBox_2, {
							"top": "35px",
							"left": "265px",
							"width": "95px",
							"height": "25px"
						});
						var output_4 = new cpr.controls.Output("optMsgDivRcd1");
						output_4.value = "대구분";
						container.addChild(output_4, {
							"top": "90px",
							"left": "5px",
							"width": "60px",
							"height": "25px"
						});
						var comboBox_3 = new cpr.controls.ComboBox("cbbMsgDivRcd1");
						comboBox_3.bind("fieldLabel").toExpression("#optMsgDivRcd.value");
						comboBox_3.bind("value").toDataMap(app.lookup("dmReqList"), "strMsgDivRcd");
						(function(comboBox_3){
							comboBox_3.setItemSet(app.lookup("dsMsgDivRcdList"), {
								"label": "CD_NM",
								"value": "CD"
							});
						})(comboBox_3);
						container.addChild(comboBox_3, {
							"top": "90px",
							"left": "70px",
							"width": "130px",
							"height": "25px"
						});
						var output_5 = new cpr.controls.Output("optMsgSubDivRcd1");
						output_5.value = "소구분";
						container.addChild(output_5, {
							"top": "90px",
							"left": "205px",
							"width": "55px",
							"height": "25px"
						});
						var comboBox_4 = new cpr.controls.ComboBox("cbbMsgSubDivRcd1");
						comboBox_4.multiple = true;
						comboBox_4.bind("fieldLabel").toExpression("#optMsgSubDivRcd.value");
						comboBox_4.bind("value").toDataMap(app.lookup("dmReqList"), "strMsgSubDivRcd");
						(function(comboBox_4){
							comboBox_4.setItemSet(app.lookup("dsReqList"), {
								"label": "CD_NM",
								"value": "CD"
							});
						})(comboBox_4);
						if(typeof onCbbMsgSubDivRcd1Focus == "function") {
							comboBox_4.addEventListener("focus", onCbbMsgSubDivRcd1Focus);
						}
						container.addChild(comboBox_4, {
							"top": "90px",
							"left": "265px",
							"width": "95px",
							"height": "25px"
						});
						var userDefinedControl_3 = new udc.com.comFormTitle();
						userDefinedControl_3.bind("title").toLanguage("");
						container.addChild(userDefinedControl_3, {
							"top": "5px",
							"left": "5px",
							"width": "200px",
							"height": "25px"
						});
						var userDefinedControl_4 = new udc.com.comFormTitle();
						userDefinedControl_4.bind("title").toLanguage("");
						container.addChild(userDefinedControl_4, {
							"top": "65px",
							"left": "5px",
							"width": "395px",
							"height": "25px"
						});
						var output_6 = new cpr.controls.Output("label6");
						output_6.value = "콤보 검색기능 적용시 suggest=true";
						container.addChild(output_6, {
							"top": "6px",
							"left": "199px",
							"width": "251px",
							"height": "25px"
						});
						var listBox_1 = new cpr.controls.ListBox("listbox1");
						listBox_1.multiple = true;
						listBox_1.bind("value").toDataMap(app.lookup("dmSelect"), "listbox1");
						(function(listBox_1){
							listBox_1.setItemSet(app.lookup("dsMsgSubDivRcdList"), {
								"label": "CD_NM",
								"value": "CD"
							})
						})(listBox_1);
						if(typeof onListbox1ValueChange == "function") {
							listBox_1.addEventListener("value-change", onListbox1ValueChange);
						}
						container.addChild(listBox_1, {
							"top": "145px",
							"left": "10px",
							"width": "140px",
							"height": "147px"
						});
						var textArea_1 = new cpr.controls.TextArea("textarea1");
						container.addChild(textArea_1, {
							"top": "150px",
							"left": "165px",
							"width": "175px",
							"height": "145px"
						});
						var userDefinedControl_5 = new udc.com.comFormTitle();
						userDefinedControl_5.bind("title").toLanguage("");
						container.addChild(userDefinedControl_5, {
							"top": "120px",
							"left": "5px",
							"width": "395px",
							"height": "25px"
						});
					})(group_4);
					tabItem_2.content = group_4;
					return tabItem_2;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_2);
				
				var tabItem_3 = (function(tabFolder){
					var tabItem_3 = new cpr.controls.TabItem();
					tabItem_3.text = "tab1";
					tabItem_3.name = "Input";
					var group_5 = new cpr.controls.Container("grpInput");
					// Layout
					var formLayout_3 = new cpr.controls.layouts.FormLayout();
					formLayout_3.topMargin = "0px";
					formLayout_3.rightMargin = "0px";
					formLayout_3.bottomMargin = "0px";
					formLayout_3.leftMargin = "0px";
					formLayout_3.horizontalSpacing = "0px";
					formLayout_3.verticalSpacing = "0px";
					formLayout_3.setColumns(["1fr"]);
					formLayout_3.setRows(["1fr"]);
					group_5.setLayout(formLayout_3);
					(function(container){
						var group_6 = new cpr.controls.Container("group15");
						// Layout
						var xYLayout_4 = new cpr.controls.layouts.XYLayout();
						group_6.setLayout(xYLayout_4);
						(function(container){
							var userDefinedControl_6 = new udc.com.comFormTitle();
							userDefinedControl_6.bind("title").toLanguage("");
							container.addChild(userDefinedControl_6, {
								"top": "5px",
								"left": "5px",
								"width": "150px",
								"height": "25px"
							});
							var output_7 = new cpr.controls.Output("label12");
							output_7.value = "대문자+숫자";
							output_7.style.css({
								"text-align" : "right"
							});
							container.addChild(output_7, {
								"top": "60px",
								"left": "5px",
								"width": "100px",
								"height": "25px"
							});
							var inputBox_1 = new cpr.controls.InputBox("inputbox2");
							inputBox_1.maxLength = 10;
							container.addChild(inputBox_1, {
								"top": "60px",
								"left": "110px",
								"width": "100px",
								"height": "25px"
							});
							var output_8 = new cpr.controls.Output("label18");
							output_8.value = "대문자만";
							output_8.style.css({
								"text-align" : "right"
							});
							container.addChild(output_8, {
								"top": "93px",
								"left": "5px",
								"width": "100px",
								"height": "25px"
							});
							var inputBox_2 = new cpr.controls.InputBox("inputbox3");
							inputBox_2.maxLength = 10;
							container.addChild(inputBox_2, {
								"top": "93px",
								"left": "110px",
								"width": "100px",
								"height": "25px"
							});
							var output_9 = new cpr.controls.Output("label13");
							output_9.value = "소문자+숫자";
							output_9.style.css({
								"text-align" : "right"
							});
							container.addChild(output_9, {
								"top": "126px",
								"left": "5px",
								"width": "100px",
								"height": "25px"
							});
							var inputBox_3 = new cpr.controls.InputBox("inputbox8");
							inputBox_3.maxLength = 10;
							container.addChild(inputBox_3, {
								"top": "126px",
								"left": "110px",
								"width": "100px",
								"height": "25px"
							});
							var output_10 = new cpr.controls.Output("label23");
							output_10.value = "number";
							container.addChild(output_10, {
								"top": "24px",
								"left": "235px",
								"width": "100px",
								"height": "25px"
							});
							var output_11 = new cpr.controls.Output("label14");
							output_11.value = "금액";
							output_11.style.css({
								"text-align" : "right"
							});
							container.addChild(output_11, {
								"top": "55px",
								"left": "235px",
								"width": "100px",
								"height": "25px"
							});
							var output_12 = new cpr.controls.Output("label8");
							output_12.value = "소수점";
							output_12.style.css({
								"text-align" : "right"
							});
							container.addChild(output_12, {
								"top": "90px",
								"left": "235px",
								"width": "100px",
								"height": "25px"
							});
							var numberEditor_1 = new cpr.controls.NumberEditor("inputbox7");
							container.addChild(numberEditor_1, {
								"top": "95px",
								"left": "340px",
								"width": "100px",
								"height": "25px"
							});
							var numberEditor_2 = new cpr.controls.NumberEditor("inputbox9");
							numberEditor_2.format = "9,999,999,999";
							container.addChild(numberEditor_2, {
								"top": "60px",
								"left": "340px",
								"width": "100px",
								"height": "25px"
							});
							var output_13 = new cpr.controls.Output("label24");
							output_13.value = "date";
							output_13.style.css({
								"text-align" : "right"
							});
							container.addChild(output_13, {
								"top": "24px",
								"left": "485px",
								"width": "100px",
								"height": "25px"
							});
							var dateInput_1 = new cpr.controls.DateInput("inputbox11");
							container.addChild(dateInput_1, {
								"top": "61px",
								"left": "590px",
								"width": "100px",
								"height": "25px"
							});
							var output_14 = new cpr.controls.Output("label17");
							output_14.value = "시간";
							output_14.style.css({
								"text-align" : "right"
							});
							container.addChild(output_14, {
								"top": "95px",
								"left": "485px",
								"width": "100px",
								"height": "25px"
							});
							var inputBox_4 = new cpr.controls.InputBox("inputbox10");
							container.addChild(inputBox_4, {
								"top": "159px",
								"left": "110px",
								"width": "100px",
								"height": "25px"
							});
							var output_15 = new cpr.controls.Output("label7");
							output_15.value = "전화번호";
							output_15.style.css({
								"text-align" : "right"
							});
							container.addChild(output_15, {
								"top": "159px",
								"left": "5px",
								"width": "100px",
								"height": "25px"
							});
							var numberEditor_3 = new cpr.controls.NumberEditor("inputbox4");
							numberEditor_3.bind("value").toDataMap(app.lookup("dmRoot"), "input");
							container.addChild(numberEditor_3, {
								"top": "126px",
								"left": "343px",
								"width": "100px",
								"height": "25px"
							});
							var output_16 = new cpr.controls.Output("label9");
							output_16.value = "학점";
							output_16.style.css({
								"text-align" : "right"
							});
							container.addChild(output_16, {
								"top": "126px",
								"left": "234px",
								"width": "100px",
								"height": "25px"
							});
							var dateInput_2 = new cpr.controls.DateInput("inputbox12");
							dateInput_2.bind("value").toDataMap(app.lookup("dmInput"), "lowcaseNum");
							container.addChild(dateInput_2, {
								"top": "95px",
								"left": "590px",
								"width": "100px",
								"height": "25px"
							});
							var output_17 = new cpr.controls.Output("label10");
							output_17.value = "string";
							container.addChild(output_17, {
								"top": "24px",
								"left": "5px",
								"width": "100px",
								"height": "25px"
							});
							var output_18 = new cpr.controls.Output("label11");
							output_18.value = "날짜";
							output_18.style.css({
								"text-align" : "right"
							});
							container.addChild(output_18, {
								"top": "61px",
								"left": "485px",
								"width": "100px",
								"height": "25px"
							});
							var button_1 = new cpr.controls.Button("button1");
							button_1.value = "input test";
							if(typeof onButton1Click == "function") {
								button_1.addEventListener("click", onButton1Click);
							}
							container.addChild(button_1, {
								"top": "5px",
								"left": "875px",
								"width": "80px",
								"height": "25px"
							});
						})(group_6);
						container.addChild(group_6, {
							"top": "5px",
							"left": "5px",
							"width": "960px",
							"height": "452px"
						});
					})(group_5);
					tabItem_3.content = group_5;
					return tabItem_3;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_3);
				
				var tabItem_4 = (function(tabFolder){
					var tabItem_4 = new cpr.controls.TabItem();
					tabItem_4.text = "tab1";
					tabItem_4.name = "ETC";
					var group_7 = new cpr.controls.Container("grpETC");
					// Layout
					var formLayout_4 = new cpr.controls.layouts.FormLayout();
					formLayout_4.topMargin = "0px";
					formLayout_4.rightMargin = "0px";
					formLayout_4.bottomMargin = "0px";
					formLayout_4.leftMargin = "0px";
					formLayout_4.horizontalSpacing = "0px";
					formLayout_4.verticalSpacing = "0px";
					formLayout_4.setColumns(["1fr"]);
					formLayout_4.setRows(["1fr"]);
					group_7.setLayout(formLayout_4);
					(function(container){
						var textArea_2 = new cpr.controls.TextArea("textarea2");
						container.addChild(textArea_2, {
							"top": "15px",
							"left": "150px",
							"width": "265px",
							"height": "215px"
						});
						var button_2 = new cpr.controls.Button("button2");
						button_2.value = "getXML";
						if(typeof onButton2Click == "function") {
							button_2.addEventListener("click", onButton2Click);
						}
						container.addChild(button_2, {
							"top": "15px",
							"left": "20px",
							"width": "110px",
							"height": "25px"
						});
						var listBox_2 = new cpr.controls.ListBox("listbox2");
						listBox_2.multiple = true;
						listBox_2.bind("value").toDataMap(app.lookup("dmEtc"), "listbox2");
						(function(listBox_2){
							listBox_2.setItemSet(app.lookup("dsLsbPgmInfo"), {
								"label": "pgm_nm",
								"value": "pgm_id"
							})
						})(listBox_2);
						if(typeof onListbox2ValueChange == "function") {
							listBox_2.addEventListener("value-change", onListbox2ValueChange);
						}
						container.addChild(listBox_2, {
							"top": "270px",
							"left": "5px",
							"width": "230px",
							"height": "225px"
						});
						var userDefinedControl_7 = new udc.com.comFormTitle();
						userDefinedControl_7.bind("title").toLanguage("");
						container.addChild(userDefinedControl_7, {
							"top": "240px",
							"left": "5px",
							"width": "150px",
							"height": "25px"
						});
					})(group_7);
					tabItem_4.content = group_7;
					return tabItem_4;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_4);
				
				var tabItem_5 = (function(tabFolder){
					var tabItem_5 = new cpr.controls.TabItem();
					tabItem_5.text = "tab1";
					tabItem_5.name = "ValidUtil";
					var group_8 = new cpr.controls.Container("grpValidUtil");
					// Layout
					var formLayout_5 = new cpr.controls.layouts.FormLayout();
					formLayout_5.topMargin = "0px";
					formLayout_5.rightMargin = "0px";
					formLayout_5.bottomMargin = "0px";
					formLayout_5.leftMargin = "0px";
					formLayout_5.horizontalSpacing = "0px";
					formLayout_5.verticalSpacing = "0px";
					formLayout_5.setColumns(["1fr"]);
					formLayout_5.setRows(["1fr"]);
					group_8.setLayout(formLayout_5);
					(function(container){
						var inputBox_5 = new cpr.controls.InputBox("ipbValue");
						inputBox_5.bind("fieldLabel").toExpression("#optValue.value");
						inputBox_5.bind("value").toDataMap(app.lookup("dmValid"), "strInput");
						container.addChild(inputBox_5, {
							"top": "45px",
							"left": "10px",
							"width": "105px",
							"height": "30px"
						});
						var button_3 = new cpr.controls.Button("button3");
						button_3.value = "ValidUtil.check";
						if(typeof onButton3Click == "function") {
							button_3.addEventListener("click", onButton3Click);
						}
						container.addChild(button_3, {
							"top": "45px",
							"left": "284px",
							"width": "161px",
							"height": "25px"
						});
						var output_19 = new cpr.controls.Output("optValue");
						output_19.value = "입력값";
						output_19.style.css({
							"text-align" : "center"
						});
						container.addChild(output_19, {
							"top": "15px",
							"left": "10px",
							"width": "105px",
							"height": "25px"
						});
						var button_4 = new cpr.controls.Button("button4");
						button_4.value = "ValidUtil.checkValue";
						if(typeof onButton4Click == "function") {
							button_4.addEventListener("click", onButton4Click);
						}
						container.addChild(button_4, {
							"top": "45px",
							"left": "453px",
							"width": "201px",
							"height": "25px"
						});
						var comboBox_5 = new cpr.controls.ComboBox("cbbProp");
						comboBox_5.bind("value").toDataMap(app.lookup("dmValid"), "strCbb");
						(function(comboBox_5){
							comboBox_5.addItem(new cpr.controls.Item("notNull", "notNull=yes"));
							comboBox_5.addItem(new cpr.controls.Item("length", "length=2"));
							comboBox_5.addItem(new cpr.controls.Item("byteLength", "byteLength=4"));
							comboBox_5.addItem(new cpr.controls.Item("minLength", "minLength=3"));
							comboBox_5.addItem(new cpr.controls.Item("minByteLength", "minByteLength=4"));
							comboBox_5.addItem(new cpr.controls.Item("maxLength", "maxLength=4"));
							comboBox_5.addItem(new cpr.controls.Item("maxByteLength", "maxByteLength=4"));
							comboBox_5.addItem(new cpr.controls.Item("number", "number"));
							comboBox_5.addItem(new cpr.controls.Item("minNumber", "minNumber=3"));
							comboBox_5.addItem(new cpr.controls.Item("maxNumber", "maxNumber=5"));
							comboBox_5.addItem(new cpr.controls.Item("inNumber", "inNumber=1~5"));
							comboBox_5.addItem(new cpr.controls.Item("minDate", "minDate=20150101"));
							comboBox_5.addItem(new cpr.controls.Item("maxDate", "maxDate=20150101"));
							comboBox_5.addItem(new cpr.controls.Item("format", "format=h"));
							comboBox_5.addItem(new cpr.controls.Item("ssn", "ssn"));
							comboBox_5.addItem(new cpr.controls.Item("csn", "csn"));
							comboBox_5.addItem(new cpr.controls.Item("filterIn", "filterIn=\\h"));
							comboBox_5.addItem(new cpr.controls.Item("filterOut", "filterOut=2;3"));
							comboBox_5.addItem(new cpr.controls.Item("email", "email"));
							comboBox_5.addItem(new cpr.controls.Item("date", "date=YYYY"));
							comboBox_5.addItem(new cpr.controls.Item("xorNull", "xorNull=ipbValue2"));
							comboBox_5.addItem(new cpr.controls.Item("compare", "compare(ipbValue2,<=)"));
						})(comboBox_5);
						if(typeof onCbbPropSelectionChange == "function") {
							comboBox_5.addEventListener("selection-change", onCbbPropSelectionChange);
						}
						container.addChild(comboBox_5, {
							"top": "45px",
							"left": "125px",
							"width": "145px",
							"height": "30px"
						});
						var output_20 = new cpr.controls.Output("optNotNull1");
						output_20.value = "속성";
						output_20.style.css({
							"text-align" : "center"
						});
						container.addChild(output_20, {
							"top": "15px",
							"left": "125px",
							"width": "140px",
							"height": "25px"
						});
						var output_21 = new cpr.controls.Output("optValue");
						output_21.value = "";
						container.addChild(output_21, {
							"top": "15px",
							"left": "270px",
							"width": "460px",
							"height": "25px"
						});
						var inputBox_6 = new cpr.controls.InputBox("ipbValue2");
						inputBox_6.visible = false;
						inputBox_6.bind("fieldLabel").toExpression("#optValue2.value");
						inputBox_6.bind("value").toDataMap(app.lookup("dmValid"), "strInput2");
						container.addChild(inputBox_6, {
							"top": "115px",
							"left": "10px",
							"width": "105px",
							"height": "30px"
						});
						var output_22 = new cpr.controls.Output("optValue2");
						output_22.value = "입력값2";
						container.addChild(output_22, {
							"top": "85px",
							"left": "10px",
							"width": "105px",
							"height": "25px"
						});
					})(group_8);
					tabItem_5.content = group_8;
					return tabItem_5;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_5);
				
				var tabItem_6 = (function(tabFolder){
					var tabItem_6 = new cpr.controls.TabItem();
					tabItem_6.text = "tab1";
					tabItem_6.name = "DynRepeat";
					var group_9 = new cpr.controls.Container("grpDynRepeat");
					// Layout
					var formLayout_6 = new cpr.controls.layouts.FormLayout();
					formLayout_6.topMargin = "0px";
					formLayout_6.rightMargin = "0px";
					formLayout_6.bottomMargin = "0px";
					formLayout_6.leftMargin = "0px";
					formLayout_6.horizontalSpacing = "0px";
					formLayout_6.verticalSpacing = "0px";
					formLayout_6.setColumns(["1fr"]);
					formLayout_6.setRows(["1fr"]);
					group_9.setLayout(formLayout_6);
					(function(container){
						var grid_2 = new cpr.controls.Grid("dynRpt");
						grid_2.init({
							"dataSet": app.lookup("dsDynic"),
							"columns": [{"width": "40px"}],
							"header": {
								"rows": [{"height": "27px"}],
								"cells": [{
									"constraint": {"rowIndex": 0, "colIndex": 0},
									"configurator": function(cell){
										cell.text = "No";
									}
								}]
							},
							"detail": {
								"rows": [{"height": "25px"}],
								"cells": [{
									"constraint": {"rowIndex": 0, "colIndex": 0},
									"configurator": function(cell){
										cell.columnType = "rowindex";
										cell.style.css({
											"text-align" : "center"
										});
									}
								}]
							}
						});
						container.addChild(grid_2, {
							"top": "15px",
							"left": "15px",
							"width": "490px",
							"height": "155px"
						});
						var button_5 = new cpr.controls.Button("btnDyRpt");
						button_5.value = "다이나믹리피트";
						if(typeof onBtnDyRptClick == "function") {
							button_5.addEventListener("click", onBtnDyRptClick);
						}
						container.addChild(button_5, {
							"top": "15px",
							"left": "523px",
							"width": "140px",
							"height": "30px"
						});
					})(group_9);
					tabItem_6.content = group_9;
					return tabItem_6;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_6);
				
				var tabItem_7 = (function(tabFolder){
					var tabItem_7 = new cpr.controls.TabItem();
					tabItem_7.text = "tab1";
					tabItem_7.name = "slide";
					var group_10 = new cpr.controls.Container("grpslide");
					// Layout
					var formLayout_7 = new cpr.controls.layouts.FormLayout();
					formLayout_7.topMargin = "0px";
					formLayout_7.rightMargin = "0px";
					formLayout_7.bottomMargin = "0px";
					formLayout_7.leftMargin = "0px";
					formLayout_7.horizontalSpacing = "0px";
					formLayout_7.verticalSpacing = "0px";
					formLayout_7.setColumns(["1fr"]);
					formLayout_7.setRows(["1fr"]);
					group_10.setLayout(formLayout_7);
					(function(container){
					})(group_10);
					tabItem_7.content = group_10;
					return tabItem_7;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_7);
				
				var tabItem_8 = (function(tabFolder){
					var tabItem_8 = new cpr.controls.TabItem();
					tabItem_8.text = "tab1";
					tabItem_8.name = "slide1_case1";
					var group_11 = new cpr.controls.Container("grpslide1_case1");
					// Layout
					var formLayout_8 = new cpr.controls.layouts.FormLayout();
					formLayout_8.topMargin = "0px";
					formLayout_8.rightMargin = "0px";
					formLayout_8.bottomMargin = "0px";
					formLayout_8.leftMargin = "0px";
					formLayout_8.horizontalSpacing = "0px";
					formLayout_8.verticalSpacing = "0px";
					formLayout_8.setColumns(["1fr"]);
					formLayout_8.setRows(["1fr"]);
					group_11.setLayout(formLayout_8);
					(function(container){
						var output_23 = new cpr.controls.Output("label3");
						output_23.value = "label3";
						container.addChild(output_23, {
							"top": "190px",
							"left": "70px",
							"width": "270px",
							"height": "85px"
						});
					})(group_11);
					tabItem_8.content = group_11;
					return tabItem_8;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_8);
				
				var tabItem_9 = (function(tabFolder){
					var tabItem_9 = new cpr.controls.TabItem();
					tabItem_9.text = "tab1";
					tabItem_9.name = "slide1_case21";
					var group_12 = new cpr.controls.Container("grpslide1_case21");
					// Layout
					var formLayout_9 = new cpr.controls.layouts.FormLayout();
					formLayout_9.topMargin = "0px";
					formLayout_9.rightMargin = "0px";
					formLayout_9.bottomMargin = "0px";
					formLayout_9.leftMargin = "0px";
					formLayout_9.horizontalSpacing = "0px";
					formLayout_9.verticalSpacing = "0px";
					formLayout_9.setColumns(["1fr"]);
					formLayout_9.setRows(["1fr"]);
					group_12.setLayout(formLayout_9);
					(function(container){
						var inputBox_7 = new cpr.controls.InputBox("inputbox1");
						container.addChild(inputBox_7, {
							"top": "185px",
							"left": "200px",
							"width": "265px",
							"height": "85px"
						});
					})(group_12);
					tabItem_9.content = group_12;
					return tabItem_9;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_9);
				
				var tabItem_10 = (function(tabFolder){
					var tabItem_10 = new cpr.controls.TabItem();
					tabItem_10.text = "tab1";
					tabItem_10.name = "slide1_case31";
					var group_13 = new cpr.controls.Container("grpslide1_case31");
					// Layout
					var formLayout_10 = new cpr.controls.layouts.FormLayout();
					formLayout_10.topMargin = "0px";
					formLayout_10.rightMargin = "0px";
					formLayout_10.bottomMargin = "0px";
					formLayout_10.leftMargin = "0px";
					formLayout_10.horizontalSpacing = "0px";
					formLayout_10.verticalSpacing = "0px";
					formLayout_10.setColumns(["1fr"]);
					formLayout_10.setRows(["1fr"]);
					group_13.setLayout(formLayout_10);
					(function(container){
					})(group_13);
					tabItem_10.content = group_13;
					return tabItem_10;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_10);
				
				var tabItem_11 = (function(tabFolder){
					var tabItem_11 = new cpr.controls.TabItem();
					tabItem_11.text = "tab1";
					tabItem_11.name = "jsp";
					var group_14 = new cpr.controls.Container("grpjsp");
					// Layout
					var formLayout_11 = new cpr.controls.layouts.FormLayout();
					formLayout_11.topMargin = "0px";
					formLayout_11.rightMargin = "0px";
					formLayout_11.bottomMargin = "0px";
					formLayout_11.leftMargin = "0px";
					formLayout_11.horizontalSpacing = "0px";
					formLayout_11.verticalSpacing = "0px";
					formLayout_11.setColumns(["1fr"]);
					formLayout_11.setRows(["1fr"]);
					group_14.setLayout(formLayout_11);
					(function(container){
						var hTMLObject_1 = new cpr.controls.HTMLObject("htmlobject1");
						container.addChild(hTMLObject_1, {
							"top": "5px",
							"left": "5px",
							"width": "750px",
							"height": "118px"
						});
						var button_6 = new cpr.controls.Button("button10");
						button_6.value = "jsp 임포트";
						if(typeof onButton10Click == "function") {
							button_6.addEventListener("click", onButton10Click);
						}
						container.addChild(button_6, {
							"top": "5px",
							"left": "770px",
							"width": "100px",
							"height": "25px"
						});
					})(group_14);
					tabItem_11.content = group_14;
					return tabItem_11;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_11);
				tabFolder_1.setSelectedTabItem(tabItem_1);
				container.addChild(tabFolder_1, {
					"top": "35px",
					"left": "5px",
					"width": "1215px",
					"height": "553px"
				});
				var button_7 = new cpr.controls.Button("tabBtnRpt");
				button_7.value = "Repeat";
				container.addChild(button_7, {
					"top": "7px",
					"left": "8px",
					"width": "100px",
					"height": "28px"
				});
				var button_8 = new cpr.controls.Button("tabBtnSelect");
				button_8.value = "Select";
				container.addChild(button_8, {
					"top": "7px",
					"left": "109px",
					"width": "100px",
					"height": "28px"
				});
				var button_9 = new cpr.controls.Button("tabBtnInput");
				button_9.value = "Input";
				container.addChild(button_9, {
					"top": "7px",
					"left": "210px",
					"width": "100px",
					"height": "28px"
				});
				var button_10 = new cpr.controls.Button("tabBtnEtc");
				button_10.value = "ETC";
				container.addChild(button_10, {
					"top": "7px",
					"left": "313px",
					"width": "100px",
					"height": "28px"
				});
				var button_11 = new cpr.controls.Button("tabBtnValid");
				button_11.value = "Valid";
				container.addChild(button_11, {
					"top": "8px",
					"left": "416px",
					"width": "100px",
					"height": "28px"
				});
				var button_12 = new cpr.controls.Button("tabBtnDynRpt");
				button_12.value = "DynRepeat";
				container.addChild(button_12, {
					"top": "8px",
					"left": "517px",
					"width": "100px",
					"height": "28px"
				});
				var button_13 = new cpr.controls.Button("tabBtnDynRpt1");
				button_13.value = "Slide";
				container.addChild(button_13, {
					"top": "8px",
					"left": "619px",
					"width": "100px",
					"height": "28px"
				});
				var button_14 = new cpr.controls.Button("tabBtnDynRpt2");
				button_14.value = "Jsp";
				container.addChild(button_14, {
					"top": "8px",
					"left": "723px",
					"width": "100px",
					"height": "28px"
				});
			})(group_2);
			container.addChild(group_2, {
				"top": "72px",
				"left": "5px",
				"width": "1225px",
				"height": "598px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "Untitled";
	cpr.core.Platform.INSTANCE.register(app);
})();
